version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: interview-backend:latest
    depends_on:
      - postgres
    links:
      - 'postgres:postgres'
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_SERVER_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=interview_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview_db
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres:
