spring:
  application:
    name: interview
  datasource:
    url: jdbc:postgresql://${DB_SERVER_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:interview_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
  servlet:
    context-path: /altech-interview

logging:
  level:
    org.altech.interview: DEBUG
    org.springframework.web: DEBUG